### ISSUE TITLE
Dictionary mapping

### ISSUE THREAD

**Issue by veremenko-jav** [agileobjects/AgileMapper#6]
While trying to map `Dictionary<string, int>`
```
  "message": "An error has occurred.",
  "exceptionMessage": "Property 'Int32 Count' is not defined for type 'System.Collections.Generic.Dictionary`2[System.String,System.Int32]'",
  "exceptionType": "System.ArgumentException",
  "stackTrace": "   at System.Linq.Expressions.Expression.Property(Expression expression, PropertyInfo property)
   at AgileObjects.AgileMapper.ObjectPopulation.EnumerablePopulationBuilder.GetTargetVariableValue()
   at AgileObjects.AgileMapper.ObjectPopulation.CopySourceEnumerablePopulationStrategy.GetEnumerablePopulation(EnumerablePopulationBuilder builder, IObjectMappingData mappingData)
   at AgileObjects.AgileMapper.ObjectPopulation.EnumerableMappingExpressionFactory.<GetObjectPopulation>d__5.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at AgileObjects.AgileMapper.ObjectPopulation.MappingExpressionFactoryBase.Create(IObjectMappingData mappingData)
   at AgileObjects.AgileMapper.ObjectPopulation.ObjectMapperFactory.Create[TSource,TTarget](ObjectMappingData`2 mappingData)
   at AgileObjects.AgileMapper.ObjectPopulation.ObjectMappingData`2.get_Mapper()
   at AgileObjects.AgileMapper.ObjectPopulation.MappingFactory.GetInlineMappingBlock(IObjectMappingData childMappingData, MethodInfo createMethod, MappingValues mappingValues, Expression[] createMethodCallArguments)
   at AgileObjects.AgileMapper.DataSources.DataSourceFinder.GetFinalDataSource(IDataSource foundDataSource, Int32 dataSourceIndex, IMemberMappingData childMappingData)
   at AgileObjects.AgileMapper.DataSources.DataSourceFinder.<GetSourceMemberDataSources>d__7.MoveNext()
   at AgileObjects.AgileMapper.DataSources.DataSourceFinder.<EnumerateDataSources>d__3.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at AgileObjects.AgileMapper.DataSources.DataSourceFinder.FindFor(IMemberMappingData childMappingData)
   at AgileObjects.AgileMapper.ObjectPopulation.MemberPopulationFactory.Create(Member targetMember, IObjectMappingData mappingData)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at AgileObjects.AgileMapper.ObjectPopulation.ComplexTypeMappingExpressionFactory.<GetPopulationsAndCallbacks>d__15.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at AgileObjects.AgileMapper.ObjectPopulation.ComplexTypeMappingExpressionFactory.<GetObjectPopulation>d__9.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at AgileObjects.AgileMapper.ObjectPopulation.MappingExpressionFactoryBase.Create(IObjectMappingData mappingData)
   at AgileObjects.AgileMapper.ObjectPopulation.ObjectMapperFactory.Create[TSource,TTarget](ObjectMappingData`2 mappingData)
   at AgileObjects.AgileMapper.ObjectPopulation.ObjectMappingData`2.get_Mapper()
   at AgileObjects.AgileMapper.ObjectPopulation.MappingFactory.GetInlineMappingBlock(IObjectMappingData childMappingData, MethodInfo createMethod, MappingValues mappingValues, Expression[] createMethodCallArguments)
   at AgileObjects.AgileMapper.ObjectPopulation.DerivedComplexTypeMappingsFactory.AddDerivedSourceTypeMappings(IEnumerable`1 derivedSourceTypes, IObjectMappingData declaredTypeMappingData, ICollection`1 typedObjectVariables, ICollection`1 derivedTypeMappings)
   at AgileObjects.AgileMapper.ObjectPopulation.DerivedComplexTypeMappingsFactory.CreateFor(IObjectMappingData declaredTypeMappingData)
   at AgileObjects.AgileMapper.ObjectPopulation.MappingExpressionFactoryBase.Create(IObjectMappingData mappingData)
   at AgileObjects.AgileMapper.ObjectPopulation.ObjectMapperFactory.Create[TSource,TTarget](ObjectMappingData`2 mappingData)
   at AgileObjects.AgileMapper.ObjectPopulation.ObjectMappingData`2.get_Mapper()
   at AgileObjects.AgileMapper.ObjectPopulation.MappingFactory.GetInlineMappingBlock(IObjectMappingData childMappingData, MethodInfo createMethod, MappingValues mappingValues, Expression[] createMethodCallArguments)
   at AgileObjects.AgileMapper.ObjectPopulation.EnumerablePopulationBuilder.GetElementConversion(Expression sourceElement, IObjectMappingData enumerableMappingData)
   at AgileObjects.AgileMapper.ObjectPopulation.EnumerablePopulationBuilder.GetPopulationLoop(Expression sourceElement, Expression loopExitCheck, Func`2 populationLoopAdapter, IObjectMappingData enumerableMappingData)
   at AgileObjects.AgileMapper.ObjectPopulation.EnumerablePopulationBuilder.AddNewItemsToTargetVariable(IObjectMappingData enumerableMappingData)
   at AgileObjects.AgileMapper.ObjectPopulation.CopySourceEnumerablePopulationStrategy.GetEnumerablePopulation(EnumerablePopulationBuilder builder, IObjectMappingData mappingData)
   at AgileObjects.AgileMapper.ObjectPopulation.EnumerableMappingExpressionFactory.<GetObjectPopulation>d__5.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at AgileObjects.AgileMapper.ObjectPopulation.MappingExpressionFactoryBase.Create(IObjectMappingData mappingData)
   at AgileObjects.AgileMapper.ObjectPopulation.ObjectMapperFactory.Create[TSource,TTarget](ObjectMappingData`2 mappingData)
   at AgileObjects.AgileMapper.ObjectPopulation.ObjectMappingData`2.get_Mapper()
   at AgileObjects.AgileMapper.ObjectPopulation.ObjectMapperFactory.<GetOrCreateRoot>b__4_0[TSource,TTarget](ObjectMapperKeyBase key)
   at AgileObjects.AgileMapper.Caching.ArrayCache`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at AgileObjects.AgileMapper.ObjectPopulation.ObjectMappingData`2..ctor(TSource source, TTarget target, Nullable`1 enumerableIndex, ObjectMapperKeyBase mapperKey, IMappingContext mappingContext, IObjectMappingData declaredTypeMappingData, IObjectMappingData parent)
   at AgileObjects.AgileMapper.ObjectPopulation.ObjectMappingDataFactory.Create[TDeclaredSource,TDeclaredTarget](TDeclaredSource source, TDeclaredTarget target, Nullable`1 enumerableIndex, Func`3 mapperKeyFactory, IMappingContext mappingContext, IObjectMappingData parent)
   at AgileObjects.AgileMapper.ObjectPopulation.ObjectMappingDataFactory.ForRoot[TSource,TTarget](TSource source, TTarget target, IMappingContext mappingContext)
   at AgileObjects.AgileMapper.MappingExecutor`1.PerformMapping[TTarget](MappingRuleSet ruleSet, TTarget existing)
   at AgileObjects.AgileMapper.MappingExecutor`1.ToANew[TResult]()
   at 
```

**Comment by SteveWilkes** [comment]
Thanks for the bug report - assuming this is happening in version 0.8, it's almost certainly fixed in the latest code, and will be fixed in the next release. I'll be putting that up in the next few days - it contains a lot of specific dictionary mapping work.

**Comment by veremenko-jav** [comment]
Awesome! Thanks for so quick reply. Actually I still have 0.7...

**Comment by SteveWilkes** [comment]
No problem - thanks for checking it out and the feedback! :)
